server:
  port: 8090
  address: 127.0.0.1
  sessionTimeout: 0

management.port: -1

spring:
  main:
    show-banner: false
  datasource:
    platform: h2
    url: "jdbc:h2:mem:"

spring.jpa.hibernate.ddl-auto: create-drop

spring.thymeleaf.cache: false